version: '3.8'
services:
  zoo1:
    hostname: zoo1
    container_name: zoo1
    extends:
      service: zoo
      file: shared/kafka.yml

  kafka1:
    hostname: kafka1
    container_name: kafka1
    extends:
      service: kafka
      file: shared/kafka.yml
    depends_on:
      - zoo1
  kafka-schema-registry:
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    extends:
      service: kafka-schema-registry
      file: shared/kafka.yml
    depends_on:
      - zoo1
      - kafka1
  kafka-rest-proxy:
    hostname: kafka-rest-proxy
    container_name: kafka-rest-proxy
    extends:
      service: kafka-rest-proxy
      file: shared/kafka.yml
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry


  kafka-connect:
    hostname: kafka-connect
    container_name: kafka-connect
    extends:
      service: kafka-connect
      file: shared/kafka.yml
    depends_on:
      - zoo1
      - kafka1
      - kafka-schema-registry
      - kafka-rest-proxy
  #
  #  kafka-ksqldb:
  #    hostname: ksqldb-server
  #    container_name: ksqldb-server
  #    extends:
  #      service: ksqldb-server
  #      file: kafka.yml
  #    depends_on:
  #      - zoo1
  #      - kafka1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://kafka-schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: kafka-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: kafka-connect:8083

volumes:
  pg_data: { }
  conduktor_data: { }
